name: Deploy GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  get_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Check if POST_URL is set
        run: |
          if [ -z "${{ vars.POST_URL }}" ]; then
            echo "POST_URL is not set."
            exit 1
          else
            echo "POST_URL is set to ${{ vars.POST_URL }}."
          fi
      - name: Fetch and clone posts repository
        run: git clone ${{ vars.POST_URL }} my_posts
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: yarn ci
      - run: npm run build
        env:
          POSTS_FOLDER: my_posts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-